name: Python CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: "2.0.0"

    - name: Setup Poetry
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry install --no-root

    - name: Install plugin for annotating test failures
      run: poetry add pytest-github-actions-annotate-failures

    - name: Lint with Ruff
      run: |
        poetry add ruff
        poetry run ruff --format=github .

    - name: Run tests
      run: |
        poetry run pytest
