name: Python CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: "2.0.0"

    - name: Setup Poetry
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry install --no-root
        poetry add ruff
        poetry add pytest-github-actions-annotate-failures

    - name: Lint code with Ruff
      run: ruff check --output-format=github
      continue-on-error: true

    - name: Check code formatting with Ruff
      run: ruff format --diff
      continue-on-error: true

    - name: Run tests
      run: |
        poetry run pytest
